name: spooker
description: TEA project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.5.3'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #For google and firebase
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  google_sign_in: ^5.1.0
  firebase_crashlytics: ^2.2.4
  firebase_performance: ^0.7.1+2  
  cloud_firestore: ^3.1.4
  flutter_form_builder: ^7.0.0
  
  #For architecture
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  #For networking
  dio: ^4.0.0
  ua_client_hints: ^1.1.0

  #For model
  json_serializable: ^6.0.1
  freezed_annotation: ^0.14.0
  
  #For DateTime
  intl: ^0.17.0
  #For Local Storage
  shared_preferences: ^2.0.7
  #Convert enum to string
  enum_to_string: ^2.0.1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  lottie: ^1.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_gen_runner: ^4.1.2
  freezed: ^0.14.0
  effective_dart: ^1.3.2
  mocktail: ^0.2.0
  mocktail_image_network: ^0.2.0

flutter_gen:
  integrations:
    flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.otf
          weight: 400
        - asset: assets/fonts/montserrat_medium.otf
          weight: 500
        - asset: assets/fonts/montserrat_bold.otf
          weight: 700
    - family: Painterz
      fonts:
        - asset: assets/fonts/painterz.ttf
