name: spooker
description: TEA project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.5.3'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #For google and firebase
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  google_sign_in: ^5.1.0
  firebase_crashlytics: ^2.2.4
  firebase_performance: ^0.8.2+1
  firebase_storage: ^10.3.4
  cloud_firestore: ^3.1.13
  flutter_form_builder: ^7.0.0
  
  #For architecture
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  #For networking
  dio: ^4.0.0
  ua_client_hints: ^1.1.0

  #For model
  json_serializable: ^6.0.1
  freezed_annotation: ^2.1.0
  
  #For DateTime
  intl: ^0.17.0
  #For Local Storage
  shared_preferences: ^2.0.7
  #Convert enum to string
  enum_to_string: ^2.0.1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  flutter_svg: ^1.1.3
  get: ^4.3.8
  lottie: ^1.2.1
  camera: ^0.10.0
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  agora_rtc_engine: ^5.3.0
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  encrypt: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_gen_runner: ^4.1.2
  freezed: ^2.1.0+1
  effective_dart: ^1.3.2
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

flutter_gen:
  integrations:
    flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/animations/confetti_splash.json
    - assets/animations/spooker_back.json
    - assets/fonts/montserrat_bold.otf
    - assets/fonts/montserrat_medium.otf
    - assets/fonts/montserrat_regular.otf
    - assets/fonts/painterz.ttf
    - assets/images/add.png
    - assets/images/alert.png
    - assets/images/artwork.png
    - assets/images/back_arrow.png
    - assets/images/back_button.png
    - assets/images/camera.png
    - assets/images/configuration.png
    - assets/images/custom_floating.png
    - assets/images/empty_image_icon.png
    - assets/images/empty_logo.png
    - assets/images/error_logo.png
    - assets/images/gallery.png
    - assets/images/google_icon.png
    - assets/images/main_logo.png
    - assets/images/mini_logo.png
    - assets/images/notifications.png
    - assets/images/paint.png
    - assets/images/reminder.png
    - assets/images/settings.png
    - assets/images/splash_logo.png
    - assets/images/take-photo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.otf
          weight: 400
        - asset: assets/fonts/montserrat_medium.otf
          weight: 500
        - asset: assets/fonts/montserrat_bold.otf
          weight: 700
    - family: Painterz
      fonts:
        - asset: assets/fonts/painterz.ttf
